### ISSUE TITLE
[BUG] How to use AppRole, specifically, how to handle secret-id?

### ISSUE THREAD

**Issue by Ramshield** [salt-extensions/saltext-vault#110]
**Description**

Hi. I am trying to integrate Vault in Saltstack, and figured out how to do this via the new (https://github.com/salt-extensions/saltext-vault) extension. But I don't get how secret-id works when using approle.
It expires every 10 minutes, do I need to renew this manually and every time I run Salt I need to restart salt-master?

I did find `salt-run vault.generate_secret_id`, but that requires a signature, and I can't find anything about that in the Salt extension documentation.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

KVM virtual machine. 

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3007.1

Python Version:
        Python: 3.10.14 (main, Apr  3 2024, 21:30:09) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.4
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.16.0
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4

Salt Extensions:
 saltext.vault: 1.3.0

Salt Package Information:
  Package Type: onedir

System Versions:
          dist: debian 12.9 bookworm
        locale: utf-8
       machine: x86_64
       release: 6.1.0-30-amd64
        system: Linux
       version: Debian GNU/Linux 12.9 bookworm
```
</details>

**Additional context**
