### ISSUE TITLE
[TECH DEBT] The pillar configuration is confusing

### ISSUE THREAD

**Issue by lkubb** [salt-extensions/saltext-vault#30]
### Description of the tech debt to be addressed, include links and screenshots
For unclear reasons, the pillar module is currently confusingly configured like this:

```yaml
- ext_pillar:
  - vault: path=foo/bar
  # or
  - vault:
      conf: path=foo/bar
```
It does not support multiple paths or any other configuration passed in the string.

It should be simplified to:
```yaml
- ext_pillar:
  - vault: foo/bar
  # or
  - vault:
      path: foo/bar
```

Since we have the attention of people migrating explicitly anyways, let's do it in the initial release.

### Versions Report
current main
