### ISSUE TITLE
[DOCS] Configuration of custom mount for salt-master to use when authentication against vault is documented incorrectly.

### ISSUE THREAD

**Issue by sscotter** [salt-extensions/saltext-vault#68]
**Description**
Documentation at https://salt-extensions.github.io/saltext-vault/topics/basic_configuration.html say it should be configured as below.

```
vault:
  auth:
    method: approle
    mount: salt-master-approle
    role_id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    secret_id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX  
```

However, this doesn't work. The salt master makes requests to the default /auth/approle/login rather than auth/salt-master-approle/login as expected.

However the documentation at https://github.com/salt-extensions/saltext-vault/blob/main/docs/ref/configuration.md#approle_mount indicates it should be

```
vault:
  auth:
    method: approle
    approle_mount: salt-master-approle
    role_id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
    secret_id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
```
Note the third line is different (`mount` vs `approle_mount`). **Using `approle_mount` works as expected.**

**Suggested Fix**
Either one of the following

* Update documentation at https://salt-extensions.github.io/saltext-vault/topics/basic_configuration.html 
* Update saltext-vault to use `auth:auth:mount` instead of `auth:auth:approle_mount` and update https://github.com/salt-extensions/saltext-vault/blob/main/docs/ref/configuration.md to match

I'll leave it to you to decide what makes the most sense.

**Location or format of documentation**
* https://salt-extensions.github.io/saltext-vault/topics/basic_configuration.html
* https://github.com/salt-extensions/saltext-vault/blob/main/docs/ref/configuration.md#approle_mount

**Additional context**
[My, discussing with myself on Salt Users discussion group trying to get the bottom of the issue.](https://groups.google.com/g/salt-users/c/Ikicfm04XRI)
